import React, { useState } from 'react';
import { FileText, Download } from 'lucide-react';
import { Button } from '../components/ui/Button';
import { Card } from '../components/ui/Card';
import { Skeleton } from '../components/ui/Skeleton';
import { mockReport } from '../data/mockReport';
import { useMockDelay } from '../hooks/useMockDelay';

const ReportSection = ({ title, items }) => (
  <div className="mb-8">
    <h3 className="font-fraunces text-xl font-medium text-emerald-900 mb-4 pb-2 border-b border-beige-200">{title}</h3>
    <ul className="space-y-3">
      {items.map((item, idx) => (
        <li key={idx} className="flex items-start text-ink-900">
          <span className="text-emerald-600 mr-3 mt-1">•</span>
          <span className="leading-relaxed">{item}</span>
        </li>
      ))}
    </ul>
  </div>
);

export function BusinessReportPage() {
  const [report, setReport] = useState(null);
  const { isLoading, runWithDelay } = useMockDelay(1500);

  const generateReport = async () => {
    setReport(null);
    await runWithDelay();
    setReport(mockReport);
  };

  return (
    <div className="p-4 md:p-8 max-w-4xl mx-auto animate-in fade-in pb-20">
      <div className="text-center mb-10">
        <h1 className="font-fraunces text-3xl text-emerald-900 mb-4">AI Business Report Generator</h1>
        <p className="text-ink-500 mb-8 max-w-lg mx-auto">
          Based on your profile, inputs, and AI recommendations, we'll put together a comprehensive business report suitable for bank loans or scheme applications.
        </p>
        {!report && (
          <Button size="lg" variant="accent" onClick={generateReport} disabled={isLoading} className="px-8 font-medium">
            {isLoading ? 'Generating Document...' : 'Generate Full Report'}
          </Button>
        )}
      </div>

      {isLoading && (
        <Card className="bg-white shadow-xl min-h-[600px] p-8 md:p-12">
          <div className="animate-pulse space-y-12">
            <div className="space-y-4">
              <Skeleton className="h-8 w-1/3 mb-6" />
              <Skeleton className="h-4 w-full" />
              <Skeleton className="h-4 w-5/6" />
              <Skeleton className="h-4 w-4/5" />
            </div>
            <div className="space-y-4">
              <Skeleton className="h-8 w-1/4 mb-6" />
              <Skeleton className="h-4 w-full" />
              <Skeleton className="h-4 w-11/12" />
            </div>
            <div className="space-y-4">
              <Skeleton className="h-8 w-2/5 mb-6" />
              <Skeleton className="h-4 w-full" />
              <Skeleton className="h-4 w-3/4" />
              <Skeleton className="h-4 w-5/6" />
            </div>
          </div>
        </Card>
      )}

      {report && !isLoading && (
        <div className="relative animate-in slide-in-from-bottom-8 duration-500">
          <div className="flex justify-end mb-4">
            <Button variant="outline" className="text-ink-500 border-beige-200" title="Coming with backend integration" disabled>
              <Download size={16} className="mr-2" /> Download PDF
            </Button>
          </div>
          
          <Card className="bg-white shadow-xl min-h-[800px] p-8 md:p-12 relative overflow-hidden">
            {/* Watermark */}
            <div className="absolute top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2 opacity-5 pointer-events-none">
              <FileText size={400} />
            </div>
            
            <div className="relative z-10">
              <div className="text-center mb-12 pb-8 border-b-2 border-emerald-900/10">
                <h2 className="font-fraunces text-3xl md:text-4xl font-bold text-emerald-900 mb-2">Project Viability Report</h2>
                <p className="text-ink-500 font-mono text-sm">Generated on {new Date().toLocaleDateString()}</p>
                <div className="inline-block mt-4 px-3 py-1 bg-emerald-50 text-emerald-700 text-xs font-bold tracking-widest uppercase rounded-full border border-emerald-200">
                  AI-Verified
                </div>
              </div>

              <ReportSection title="Market Analysis & Demand" items={report.marketAnalysis} />
              <ReportSection title="Financial Plan & Projections" items={report.financialPlan} />
              <ReportSection title="Risk Analysis & Mitigation" items={report.riskAnalysis} />
              <ReportSection title="Growth Opportunities" items={report.growthOpportunities} />
              
              <div className="mt-16 pt-8 border-t border-beige-200 text-center text-sm text-ink-500">
                <p>This document is generated by VyaparSetu's AI engine for preliminary assessment purposes.</p>
              </div>
            </div>
          </Card>
        </div>
      )}
    </div>
  );
}
